### ISSUE TITLE
no debian buster packages

### ISSUE THREAD

**Issue by synq** [eduvpn/documentation#48]
With debian buster being current stable debian version one would expect debian buster packages.

**Comment by ghost** [comment]
I totally agree! We are working on it, but it is a work in progress. Can you help us?

Work in progress: https://github.com/eduvpn/eduvpn-debian/tree/buster

**Comment by ghost** [comment]
See also the open issues: https://github.com/eduvpn/eduvpn-debian/issues

**Comment by ghost** [comment]
https://list.surfnet.nl/pipermail/eduvpn-deploy/2020-August/000290.html
