### ISSUE TITLE
EduVPN Server Specs

### ISSUE THREAD

**Issue by mbile** [eduvpn/documentation#51]
Hello,

Thanks for this great service. I would like to know the minimal requirements for EduVPN Server like CPU cores, RAM, etc. As the NREN of Somalia, We would love to deploy EduVPN for our member institutions. 

Hope to hear from you soon.

Regards,

P.S stay safe.

**Comment by ghost** [comment]
It depends on the number of concurrent users that will use the VPN and how much bandwidth you have available. See https://github.com/eduvpn/documentation/blob/v2/SCALING.md for more information. 

Feel free to contact the eduVPN team on eduvpn-support@lists.geant.org for discussing eduVPN specific issues.

**Comment by mbile** [comment]
Thanks @fkooman for the response.
