### ISSUE TITLE
CentOS RPM paths changed

### ISSUE THREAD

**Issue by gvde** [eduvpn/documentation#52]
It seems paths on the repo server changed:

```
# yum update
Loaded plugins: fastestmirror, rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
Loading mirror speeds from cached hostfile
https://repo.letsconnect-vpn.org/2/rpm/release/enterprise/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

```
# cat LC.repo 
[LC]
name=Let's Connect! Packages (EL $releasever)
baseurl=https://repo.letsconnect-vpn.org/2/rpm/release/enterprise/$releasever/$basearch
gpgcheck=1
enabled=1
gpgkey=https://repo.letsconnect-vpn.org/2/rpm/release/RPM-GPG-KEY-LC
skip_if_unavailable=False
```

The current v2 deployment scripts sets different paths. It seems no update before fixed those... That's a little bit unfortunate. Maybe the repo files should be put into a RPM file, too.

**Comment by ghost** [comment]
Sorry! I removed a symlink! Should be fixed now! Let me know if it didn't...

> Maybe the repo files should be put into a RPM file, too.

#25

**Comment by ghost** [comment]
Hope this was adequately fixed :-)

**Comment by paulhermanseu** [comment]
Today I got this error, can you check your symlink?

```
# yum update
Retrieving key from https://repo.letsconnect-vpn.org/2/rpm/release/RPM-GPG-KEY-LC
GPG key retrieval failed: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by ghost** [comment]
I'll update https://github.com/eduvpn/documentation/blob/v2/REPO.md to also include the (new) keys and not just the repository configuration.
