### ISSUE TITLE
repo.eduvpn does not have a release file in ubuntu 18.04LTS

### ISSUE THREAD

**Issue by bhagat-san** [eduvpn/documentation#60]
Ign:1 https://repo.eduvpn.org/v2/deb bionic InRelease   
Get:2 https://repo.eduvpn.org/debian stretch InRelease [9629 B]
Err:3 https://repo.eduvpn.org/v2/deb bionic Release
  404  Not Found[IP]
E: The repository 'https://repo.eduvpn.org/v2/deb bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by ghost** [comment]
That is on purpose... We'd like to keep the list of targets we are supporting and need to test to a minimum as we do not have the resources to test (extensively) on all different distributions... It is already difficult enough with all the different "flavors" of Debian and CentOS on the different VM platforms. Also, why not use Debian? Especially Debian 10 works really well and is reasonably up to date... Furthermore, we'll support Debian 11 pretty much on release day :)

That being said, you can set up your own repository and build the packages for Ubuntu using our Debian package build scripts, see https://git.sr.ht/~fkooman/builder.deb. You probably need to update the release name in some of the files and I think update the mirror in `pbuilderrc`, but I didn't test that.

**Comment by ghost** [comment]
I did create support for building Ubuntu package (20.04) now in the official builder. If you are interested in running the builder yourself to generate the repository you can do that. It will be a while before that is officially supported though. It would be nice to have someone test it...

See builder documentation on https://git.sr.ht/~fkooman/builder.deb, and specifically https://git.sr.ht/~fkooman/builder.deb#ubuntu

**Comment by ghost** [comment]
I just tested my Ubuntu 20.04 packages, it does work pretty well. To deploy on Ubuntu 20.04 LTS follow the debian installation procedures, but enable the development repo, so instead of `./deploy_debian.sh` you do `VPN_DEV_REPO=1 ./deploy_debian.sh`, the rest stays the same.

Let me know if it works for you!

(I tested with the OpenStack image found here: http://cloud-images.ubuntu.com/minimal/daily/focal/current/focal-minimal-cloudimg-amd64.img from 2021-02-19).

**Comment by ghost** [comment]
I guess OP moved on.
