### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by Maaaaary** [eduvpn/documentation#61]
Hello,

I wanted to update EduVPN and then log in again through my institution, but unfortunately I get this error. I have turned off Firefox's privacy tracker and the add-ons: uBlock Origin, HTTPS Everywhere, Decentraleyes and Privacy Badger. I also turned my cookies to 'normal' instead of 'strict'. How can this error be fixed?

![afbeelding](https://user-images.githubusercontent.com/75277448/100660947-0985d500-3353-11eb-9762-45c4068254b4.png)

**Comment by ghost** [comment]
This is typically a problem with cookies indeed. This occurs when cookies are completely turned off usually. All the add-ons you mentioned should be fine and don't need to be turned off for eduVPN, I am also using uBlock Origin and HTTPS Everywhere. Are you on Windows? Are you sure Firefox is used by the eduVPN application to do the login/authorization and not some other browser that has cookies turned off?

**Comment by Maaaaary** [comment]
Yes, I am on Windows and I don't have any other browser (except for Edge) on my laptop. I was playing with my settings and I have turned cookies on and I also use Multi-Account Containers, which could also have played a role, since EduVPN did work after I turned the add-on off. Thank you so much for your help.
