### ISSUE TITLE
Unable to configure sldap(secure ldap port 636) with eduvpn

### ISSUE THREAD

**Issue by nicsandeep** [eduvpn/documentation#65]
Is there any workaround to configure sldap(secure ldap port 636) with eduvpn??
and also where is the log file when we hit the ldap server?

**Comment by ghost** [comment]
Yes, you can use `ldaps://HOST` in the `ldapUri` option.

I also updated the documentation: https://github.com/eduvpn/documentation/commit/96eca296c4fbe319ec84549693b033c1f17e0a5e

Let me know if you have any other questions.

**Comment by nicsandeep** [comment]
Thank you François for the document.
