### ISSUE TITLE
EduVPN server is generating an excessive amount of DNS queries

### ISSUE THREAD

**Issue by bhagat-san** [eduvpn/documentation#67]
EduVPN server is generating an excessive amount of DNS queries(as noted by my DNS admin)
1. Why is it happening?
2. Is there  a command or method I can use to determine which process/service is issuing these queries?

**Comment by ghost** [comment]
What do you/your DNS admin consider excessive? Perhaps these queries are sent by a VPN client? Do you know what those queries are for? Maybe they indicate malware?

You could for example use "tcpdump" on your VPN server to log all outgoing DNS queries to the DNS server and see where they originate from (which VPN client IP). Another approach is to set up a [local DNS resolver](https://github.com/eduvpn/documentation/blob/v2/LOCAL_DNS.md) and have the VPN clients use that so you can use more extensive logging.

**Comment by bhagat-san** [comment]
As per firewall logs for 15 mins of duration hit count from eduvpn server to dns sesrver is 2050hits.

ok, I'll try tcpdump on my vpn server.

**Comment by bhagat-san** [comment]
There are no VPN clients were connected, but on firewall logs it is showing that vpn server is generating dns request.

**Comment by ghost** [comment]
DNS requests for what?
