### ISSUE TITLE
unable to open socket to ssl [111]: Connection refused

### ISSUE THREAD

**Issue by bhagat-san** [eduvpn/documentation#68]
When checking connection with #vpn-server-api-status command, error occured :
 unable to open socket to "ssl://<server IP>:41194": [111]: Connection refused
What is the reason and how to resolve it??

**Comment by ghost** [comment]
That depends on what you did after you installed you server using `deploy_${DIST}.sh`... do you have a list of all changes you made to the server before/after running that script?
