### ISSUE TITLE
Centos yum update 404 error

### ISSUE THREAD

**Issue by paulhermanseu** [eduvpn/documentation#70]
Today I got this error, seems to be the same problem as here:  https://github.com/eduvpn/documentation/issues/52

```
# yum update
Retrieving key from https://repo.letsconnect-vpn.org/2/rpm/release/RPM-GPG-KEY-LC
GPG key retrieval failed: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by ghost** [comment]
The key was updated and changed URL a long time ago already, see: https://list.surfnet.nl/pipermail/eduvpn-deploy/2021-April/000332.html

**Comment by ghost** [comment]
I'll update https://github.com/eduvpn/documentation/blob/v2/REPO.md to also include the (new) keys and not just the repository configuration.

**Comment by paulhermanseu** [comment]
Great, that worked!
