### ISSUE TITLE
NAT for both IPv4 and IPv6 client traffic is a big mistake

### ISSUE THREAD

**Issue by thomasschaeferm** [eduvpn/documentation#71]
Using NAT (address and port translation also known as MASQUERADE) with IPv6 should be avoided!

https://community.openvpn.net/openvpn/wiki/IPv6

otherwise you reintroduce all IPv4-NAT-problems again (e.g. stun, turn, alg, ice ...)

As mentioned in the openvpn wiki the best solution is to use a routed block. (/64)

In case you cant get a such a routed block you may also consider to use ndp proxys. Creating some thousands entries shouldn't be a big problem, even on a raspberry pi.

I also successfully use ndp proxys.
(creation with a loop of such commands)
ip neigh add proxy [ipv6 address] dev eth0

listing/checking with
ip neigh show proxy
2001:a61:411:fd01::1:3 dev eth0  proxy
2001:a61:411:fd01::1:5 dev eth0  proxy
2001:a61:411:fd01::1:4 dev eth0  proxy
2001:a61:411:fd01::1:7 dev eth0  proxy
2001:a61:411:fd01::1:6 dev eth0  proxy
2001:a61:411:fd01::1:9 dev eth0  proxy
2001:a61:411:fd01::1:8 dev eth0  proxy
2001:a61:411:fd01::1:a dev eth0  proxy

Of course you should replace the ULA-prefix on the client side by the global unicast addresses too.

**Comment by ghost** [comment]
I agree using NAT, not only for IPv6, but also for IPv4 is a mistake. The consideration was when creating the deploy scripts to have working IPv4 and IPv6 connectivity "out of the box". Both using routed IP space for clients, or configuring NDP proxies is not something that can easily work when deploying. Until your message I actually never knew about NDP proxy! 

So, what would you propose to do on default installations of the server? Have no IPv6 support at all out of the box? I was actually thinking about this before due to the trouble of automatically configuring IPv6 (`net.ipv6.conf.all.forwarding = 1`, `net.ipv6.conf.${EXTERNAL_IF}.accept_ra = 2`)

Perhaps the best is to have only IPv4 NAT out of the box and have a separate document on how to enable IPv6, either with routed space or NDP proxy support. Would you be willing to contribute the "NDP proxy" documentation in that case? Would it be possible to automate adding the addresses somehow through /etc/network/interfaces or NetworkManager on the server?

**Comment by thomasschaeferm** [comment]
I think IPv4 with real addresses is a lost area. People and apps now expect NAT. New IPv4 addresses are really expensive (at the moment 40USD each). 
Also people know IPv4, if they want, they know how to change it from NAT to normal.
For IPv6 the situation is different. NAT works in most cases, but it leads to trouble e.g. on video conferences.
My proposal would be: Starting with a hint, that the NAT-solution for IPv6 may work, but problems are expected.

Then I would start with a separate document about IPv6.  

Short introduction, that NAT was chosen  by having simple deploy scripts running everywhere, knowing that it is a bad compromise.


preferred IPv6 without NAT:

Requirements: a routed prefix

a routed prefix can be statically assigned or it can be requested by dhcpv6 
in case you have dhcpv6 you can start directly here:
https://wiki.debian.org/IPv6PrefixDelegation

at that point you can I think you can script again everything

in case of a static assignment you may need to ask the admin during the installation for the prefix.

Alternative, when no routed prefix is available:

The server should stand in its own (V)LAN with normal slaac and /64.
NDP-proxying may  used.

I will provide an example in more details later on.

**Comment by ghost** [comment]
We already have this: https://github.com/eduvpn/documentation/blob/v2/PUBLIC_ADDR.md

**Comment by ghost** [comment]
> My proposal would be: Starting with a hint, that the NAT-solution for IPv6 may work, but problems are expected.

That's a good idea! I mean it doesn't break more than IPv4 NAT from my understanding, and when using ULA addresses IPv4 is typically preferred in my experience... but that may not be true on all client platforms...

For most production (eduVPN) servers in The Netherlands public IPv6 addresses are used, where a /64 IP range is routed to the (public) IPv6 address of the VPN server, that is the simplest solution in any case.

**Comment by thomasschaeferm** [comment]
https://github.com/eduvpn/documentation/blob/v2/PUBLIC_ADDR.md
Ok, the people here eduvpn1.eduvpn.de didn't read it. 
It is a good point I can ask them.
ULA IPv6 addresses have a lower precedence than IPv4 addresses, not only in your case. (e.g. /etc/gai.conf defaults)

**Comment by thomasschaeferm** [comment]
I could not convince the admin of eduvpn1.eduvpn.de - one of his arguments was: 

"it is default in eduvpn docs"

The doc/install scripts should state clearly , that "**default**" is the **last** but not the **best** choice. 

About an alternative for people not having a routed prefix but a normal /64 I attached my example.
It is written in bash, not the best way - I am a bad programmer. 
It grabs the prefix, it takes a sub net of it. The last line adds the range of ndp proxies ( it may need some seconds or minutes, depending on the range you define)

Adding the proxies has to be repeated when the link goes down/up or when the prefix changes, of course.

I haven't found the function within the linux network manager, maybe a hook-script is necessary for certain situations



[example.ovpn.txt](https://github.com/eduvpn/documentation/files/6877972/example.ovpn.txt)

**Comment by ghost** [comment]
> I could not convince the admin of eduvpn1.eduvpn.de - one of his arguments was: "it is default in eduvpn docs"

What other arguments were there? :-)

I started a dedicated IPV6.md to document some stuff regarding IPv6. What do you think?

https://github.com/eduvpn/documentation/blob/v2/IPV6.md

**Comment by thomasschaeferm** [comment]
Looks good. I hope I don't split the docs more than necessary.
The other arguments were: we want hide the users,  users should not have inbound and the counter question: Why GUA at all?
And of course: it is just a test - but it is already active for all members of DFN, except those with own server gateway.

**Comment by ghost** [comment]
> Looks good. I hope I don't split the docs more than necessary.

It is already very much split unfortunately. It grew like this after the last 5 years I think. We really need a "deployers manual" :)

> The other arguments were: we want hide the users

That is also a good point, if you actually consistently get away with responding to abuse complaints by saying "we don't know". If that is an option, maybe we should also create an option to completely disable logging, i.e. bind user ID to issued IP addresses.

**Comment by thomasschaeferm** [comment]
It is getting off topic, but DFN answers abuse complaints and they log, of course. "Hide"  means here all users behind one IP address (the gateways address) , but in case of trouble they name the persons, no doubt. The intention isn't hiding like other (commercial) vpn or tor.  In my ears it was just a bad excuse.
But logging NAT isn't trivial... even if the abuse report has only the one ip address and the time stamp, I get an idea....

**Comment by ghost** [comment]
I saw DFN will be switching to public IPv6 addresses!
