### ISSUE TITLE
allow renewal - keeping address

### ISSUE THREAD

**Issue by okvittem** [eduvpn/documentation#84]
Hi,
I am using eduvpn on Ubuntu 20.04. eduvpn-client  3.1.0-1.

The client does seem to not support prolonging the session, so when
I reselect my vpn provider  I get new addresses and is stuck in my
current network sessions. and the session expiration is still ticking down to annihilation.

So I have to break the session and start a new .. after the session is ended...

**Comment by jwijenbergh** [comment]
Thanks for the issue report.

We released a new linux client that shows a renew button within 24 hours of expiry.

Note that for Ubuntu, this client supports 22.04 and 22.10

For installation instructions see https://python-eduvpn-client.readthedocs.io/en/master/installation.html

**Comment by okvittem** [comment]
E: The repository 'https://app.eduvpn.org/linux/v4/deb focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by jwijenbergh** [comment]
We currently only support 22.04 and 22.10 for ubuntu. Focal (20.04) is thus currently not supported. You can either follow the instructions to install via pip, update to ubuntu 22.04 or try to add the repository with the jammy target instead of focal and see if that works (replace `$(lsb_release -cs)` in the instructions with `jammy`)

**Comment by okvittem** [comment]
Thanks for the quick reply, I tried pointing to jammy in apt.list, but got an error message for a missing pythton3 library when starting eduvpn-client. Upgrading to ubuntu 22.04 now and will report back.

**Comment by okvittem** [comment]
Thansk : version 4.0.1 is now running on Ubuntu 22.04. 
There is a new button for selecting profile, but no Renew button - yet..
So I guess it will pop up at expiry time.

**Comment by jwijenbergh** [comment]
> Thansk : version 4.0.1 is now running on Ubuntu 22.04. There is a new button for selecting profile, but no Renew button - yet.. So I guess it will pop up at expiry time.

Great! It should be visible within 24 hours of expiry (when also at least 30 minutes have passed). If not, please make an issue on https://github.com/eduvpn/python-eduvpn-client/issues
