### ISSUE TITLE
How to create a client and connect using API?

### ISSUE THREAD

**Issue by sbmvirdi** [eduvpn/documentation#88]
Hi! I have gone through the documentation for API but i am not able to understand how can we generate a client and authorization code for that client. I want to make a user connect to my VPN using API only. but i am stuck at authorization and token step itself.

can someone help in this

**Comment by ghost** [comment]
I updated the API documentation in #87 to fix the link and instruct how to create your own OAuth client registration in the server. Does this help?

You are writing your own client to interact with the eduVPN server API, right? In that case you need to implement OAuth as specified by the API documentation.

**Comment by sbmvirdi** [comment]
i am using the oauth api to perform actions on it but that requires the user to redirect to the login page and login with the credentials. How to create these credentials for new user i am onboarding in my system using api. i see we have cli tool to create a user but can we do it using api ?

**Comment by ghost** [comment]
There are two APIs: one for eduVPN applications as used by the end-user, and an Admin API, as used by administrators. The latter one can be used to create configuration files for particular users. It is not really extensive at the moment as we didn't need any more functionality.

See: https://docs.eduvpn.org/server/v3/admin-api.html

Full user management is not something we support, and probably never will. You are probably better with e.g. an LDAP server for which many tools exist to remotely manage it and then connect the VPN server to LDAP for user authentication. If you are set on "local" accounts you could for example consider using PostgreSQL or MariaDB/MySQL and do user management through SQL (over the network).

What are you looking for exactly?
